# Generated by Django 2.2.2 on 2019-06-03 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('numero_carnet', models.CharField(blank=True, max_length=9, null=True, unique=True)),
                ('cui', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('profesion', models.CharField(choices=[('Física', 'Física'), ('Matemática', 'Matemática')], default='Matemática', max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
