# Generated by Django 2.2.2 on 2019-06-03 17:02

import Archivos.models
import Archivos.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Perfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expresion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expresion', models.TextField(default=False, validators=[Archivos.validators.validar_expresion])),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=Archivos.models.user_directory_path, validators=[Archivos.validators.validate_file_extension])),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Perfiles.Perfil')),
            ],
        ),
    ]
